site_name: journeyers - Python docs
site_dir: utils_dev/doc_python
docs_dir: utils_dev/doc_python_md
extra_css: 
  - css/custom_mkdocstrings.css
plugins:
- mkdocstrings:
    handlers: 
        python:
          paths: 
            - "utils_dev"          
            - "utils_qa/utils_for_manual_and_semi_automated_testing" 
            - "utils_qa/utils_for_manual_and_semi_automated_testing/py_utils"
          options:
            show_source: false
            show_root_heading: true